// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: pkg/network/protobuf/message.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Direction int32

const (
	Direction_UP    Direction = 0
	Direction_DOWN  Direction = 1
	Direction_LEFT  Direction = 2
	Direction_RIGHT Direction = 3
)

// Enum value maps for Direction.
var (
	Direction_name = map[int32]string{
		0: "UP",
		1: "DOWN",
		2: "LEFT",
		3: "RIGHT",
	}
	Direction_value = map[string]int32{
		"UP":    0,
		"DOWN":  1,
		"LEFT":  2,
		"RIGHT": 3,
	}
)

func (x Direction) Enum() *Direction {
	p := new(Direction)
	*p = x
	return p
}

func (x Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_network_protobuf_message_proto_enumTypes[0].Descriptor()
}

func (Direction) Type() protoreflect.EnumType {
	return &file_pkg_network_protobuf_message_proto_enumTypes[0]
}

func (x Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Direction.Descriptor instead.
func (Direction) EnumDescriptor() ([]byte, []int) {
	return file_pkg_network_protobuf_message_proto_rawDescGZIP(), []int{0}
}

type MoveMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Direction Direction `protobuf:"varint,1,opt,name=direction,proto3,enum=snakes.Direction" json:"direction,omitempty"`
}

func (x *MoveMessage) Reset() {
	*x = MoveMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_network_protobuf_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveMessage) ProtoMessage() {}

func (x *MoveMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_network_protobuf_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveMessage.ProtoReflect.Descriptor instead.
func (*MoveMessage) Descriptor() ([]byte, []int) {
	return file_pkg_network_protobuf_message_proto_rawDescGZIP(), []int{0}
}

func (x *MoveMessage) GetDirection() Direction {
	if x != nil {
		return x.Direction
	}
	return Direction_UP
}

type DisconnectMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DisconnectMessage) Reset() {
	*x = DisconnectMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_network_protobuf_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DisconnectMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectMessage) ProtoMessage() {}

func (x *DisconnectMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_network_protobuf_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectMessage.ProtoReflect.Descriptor instead.
func (*DisconnectMessage) Descriptor() ([]byte, []int) {
	return file_pkg_network_protobuf_message_proto_rawDescGZIP(), []int{1}
}

type JoinMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *JoinMessage) Reset() {
	*x = JoinMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_network_protobuf_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinMessage) ProtoMessage() {}

func (x *JoinMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_network_protobuf_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinMessage.ProtoReflect.Descriptor instead.
func (*JoinMessage) Descriptor() ([]byte, []int) {
	return file_pkg_network_protobuf_message_proto_rawDescGZIP(), []int{2}
}

func (x *JoinMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type StartGameMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StartGameMessage) Reset() {
	*x = StartGameMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_network_protobuf_message_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartGameMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartGameMessage) ProtoMessage() {}

func (x *StartGameMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_network_protobuf_message_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartGameMessage.ProtoReflect.Descriptor instead.
func (*StartGameMessage) Descriptor() ([]byte, []int) {
	return file_pkg_network_protobuf_message_proto_rawDescGZIP(), []int{3}
}

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Type:
	//
	//	*Message_Move
	//	*Message_Disconnect
	//	*Message_Join
	//	*Message_StartGame
	//	*Message_Game
	Type isMessage_Type `protobuf_oneof:"type"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_network_protobuf_message_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_network_protobuf_message_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_pkg_network_protobuf_message_proto_rawDescGZIP(), []int{4}
}

func (m *Message) GetType() isMessage_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *Message) GetMove() *MoveMessage {
	if x, ok := x.GetType().(*Message_Move); ok {
		return x.Move
	}
	return nil
}

func (x *Message) GetDisconnect() *DisconnectMessage {
	if x, ok := x.GetType().(*Message_Disconnect); ok {
		return x.Disconnect
	}
	return nil
}

func (x *Message) GetJoin() *JoinMessage {
	if x, ok := x.GetType().(*Message_Join); ok {
		return x.Join
	}
	return nil
}

func (x *Message) GetStartGame() *StartGameMessage {
	if x, ok := x.GetType().(*Message_StartGame); ok {
		return x.StartGame
	}
	return nil
}

func (x *Message) GetGame() string {
	if x, ok := x.GetType().(*Message_Game); ok {
		return x.Game
	}
	return ""
}

type isMessage_Type interface {
	isMessage_Type()
}

type Message_Move struct {
	Move *MoveMessage `protobuf:"bytes,1,opt,name=move,proto3,oneof"`
}

type Message_Disconnect struct {
	Disconnect *DisconnectMessage `protobuf:"bytes,2,opt,name=disconnect,proto3,oneof"`
}

type Message_Join struct {
	Join *JoinMessage `protobuf:"bytes,3,opt,name=join,proto3,oneof"`
}

type Message_StartGame struct {
	StartGame *StartGameMessage `protobuf:"bytes,4,opt,name=start_game,json=startGame,proto3,oneof"`
}

type Message_Game struct {
	Game string `protobuf:"bytes,6,opt,name=game,proto3,oneof"`
}

func (*Message_Move) isMessage_Type() {}

func (*Message_Disconnect) isMessage_Type() {}

func (*Message_Join) isMessage_Type() {}

func (*Message_StartGame) isMessage_Type() {}

func (*Message_Game) isMessage_Type() {}

var File_pkg_network_protobuf_message_proto protoreflect.FileDescriptor

var file_pkg_network_protobuf_message_proto_rawDesc = []byte{
	0x0a, 0x22, 0x70, 0x6b, 0x67, 0x2f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x73, 0x6e, 0x61, 0x6b, 0x65, 0x73, 0x22, 0x3e, 0x0a, 0x0b,
	0x4d, 0x6f, 0x76, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2f, 0x0a, 0x09, 0x64,
	0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11,
	0x2e, 0x73, 0x6e, 0x61, 0x6b, 0x65, 0x73, 0x2e, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x13, 0x0a, 0x11,
	0x44, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x22, 0x21, 0x0a, 0x0b, 0x4a, 0x6f, 0x69, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x22, 0x12, 0x0a, 0x10, 0x53, 0x74, 0x61, 0x72, 0x74, 0x47, 0x61, 0x6d,
	0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0xf5, 0x01, 0x0a, 0x07, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x29, 0x0a, 0x04, 0x6d, 0x6f, 0x76, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73, 0x6e, 0x61, 0x6b, 0x65, 0x73, 0x2e, 0x4d, 0x6f, 0x76, 0x65,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x04, 0x6d, 0x6f, 0x76, 0x65, 0x12,
	0x3b, 0x0a, 0x0a, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x73, 0x6e, 0x61, 0x6b, 0x65, 0x73, 0x2e, 0x44, 0x69, 0x73,
	0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00,
	0x52, 0x0a, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x29, 0x0a, 0x04,
	0x6a, 0x6f, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73, 0x6e, 0x61,
	0x6b, 0x65, 0x73, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48,
	0x00, 0x52, 0x04, 0x6a, 0x6f, 0x69, 0x6e, 0x12, 0x39, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x5f, 0x67, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x73, 0x6e,
	0x61, 0x6b, 0x65, 0x73, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x47, 0x61,
	0x6d, 0x65, 0x12, 0x14, 0x0a, 0x04, 0x67, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x00, 0x52, 0x04, 0x67, 0x61, 0x6d, 0x65, 0x42, 0x06, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x2a, 0x32, 0x0a, 0x09, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x06, 0x0a,
	0x02, 0x55, 0x50, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x44, 0x4f, 0x57, 0x4e, 0x10, 0x01, 0x12,
	0x08, 0x0a, 0x04, 0x4c, 0x45, 0x46, 0x54, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x52, 0x49, 0x47,
	0x48, 0x54, 0x10, 0x03, 0x42, 0x16, 0x5a, 0x14, 0x70, 0x6b, 0x67, 0x2f, 0x6e, 0x65, 0x74, 0x77,
	0x6f, 0x72, 0x6b, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_network_protobuf_message_proto_rawDescOnce sync.Once
	file_pkg_network_protobuf_message_proto_rawDescData = file_pkg_network_protobuf_message_proto_rawDesc
)

func file_pkg_network_protobuf_message_proto_rawDescGZIP() []byte {
	file_pkg_network_protobuf_message_proto_rawDescOnce.Do(func() {
		file_pkg_network_protobuf_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_network_protobuf_message_proto_rawDescData)
	})
	return file_pkg_network_protobuf_message_proto_rawDescData
}

var file_pkg_network_protobuf_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_network_protobuf_message_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pkg_network_protobuf_message_proto_goTypes = []interface{}{
	(Direction)(0),            // 0: snakes.Direction
	(*MoveMessage)(nil),       // 1: snakes.MoveMessage
	(*DisconnectMessage)(nil), // 2: snakes.DisconnectMessage
	(*JoinMessage)(nil),       // 3: snakes.JoinMessage
	(*StartGameMessage)(nil),  // 4: snakes.StartGameMessage
	(*Message)(nil),           // 5: snakes.Message
}
var file_pkg_network_protobuf_message_proto_depIdxs = []int32{
	0, // 0: snakes.MoveMessage.direction:type_name -> snakes.Direction
	1, // 1: snakes.Message.move:type_name -> snakes.MoveMessage
	2, // 2: snakes.Message.disconnect:type_name -> snakes.DisconnectMessage
	3, // 3: snakes.Message.join:type_name -> snakes.JoinMessage
	4, // 4: snakes.Message.start_game:type_name -> snakes.StartGameMessage
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_pkg_network_protobuf_message_proto_init() }
func file_pkg_network_protobuf_message_proto_init() {
	if File_pkg_network_protobuf_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_network_protobuf_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_network_protobuf_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DisconnectMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_network_protobuf_message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_network_protobuf_message_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartGameMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_network_protobuf_message_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_pkg_network_protobuf_message_proto_msgTypes[4].OneofWrappers = []interface{}{
		(*Message_Move)(nil),
		(*Message_Disconnect)(nil),
		(*Message_Join)(nil),
		(*Message_StartGame)(nil),
		(*Message_Game)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_network_protobuf_message_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_network_protobuf_message_proto_goTypes,
		DependencyIndexes: file_pkg_network_protobuf_message_proto_depIdxs,
		EnumInfos:         file_pkg_network_protobuf_message_proto_enumTypes,
		MessageInfos:      file_pkg_network_protobuf_message_proto_msgTypes,
	}.Build()
	File_pkg_network_protobuf_message_proto = out.File
	file_pkg_network_protobuf_message_proto_rawDesc = nil
	file_pkg_network_protobuf_message_proto_goTypes = nil
	file_pkg_network_protobuf_message_proto_depIdxs = nil
}
