name: Create Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2

        with:
          go-version: 1.19

      - name: Build Server
        run: make $(SERVER_BINARY)

      - name: Build Server
        run: make $(CLIENT_BINARY)

      - name: Upload
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          overwrite: true
          tag: ${{ github.ref }}
          asset_name: server
          file: /bin/server
