name: Update Docker Image

on:
  release:
    types: [created]

env:
  DOCKERHUB_USERNAME: alexekdahl
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  DOCKERIMG_NAME: znakes-server


jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          tag=$(echo "${{ github.ref }}" | awk -F/ '{print $NF}')
          docker build -t $DOCKERHUB_USERNAME/$DOCKERIMG_NAME:${tag} .
          docker tag $DOCKERHUB_USERNAME/$DOCKERIMG_NAME:${tag} $DOCKERHUB_USERNAME/$DOCKERIMG_NAME:latest

      - name: Push Docker image
        run: |
          echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin
          docker push $DOCKERHUB_USERNAME/$DOCKERIMG_NAME:${tag}
          docker push $DOCKERHUB_USERNAME/$DOCKERIMG_NAME:latest
