name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2

        with:
          go-version: 1.19

      - name: Build Server
        run: make $(SERVER_BINARY)

      - name: Build Server
        run: make $(CLIENT_BINARY)

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          body: Automatic release
          files: |
            bin/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload
        uses: svenstaro/upload-release-action@v2
        with:
          tag_name: ${{ github.ref }}
          name: Binary
          asset_path: ./bin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
