name: Build and Test
on: [push, pull_request]
jobs:
  build:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Generate Go code from protobuf files
        run: go generate ./...
      - name: Build project
        run: make build
      - name: Test project
        run: make test

